### ISSUE TITLE
on-chain and off-chain orders difference

### ISSUE THREAD

**Issue by narkuss** [ProjectOpenSea/seaport#1011]
I've been playing around with Seaport for a while, and i can't see the difference between off-chain and on-chain orders. 

Looking at [this cookbook](https://github.com/aegas-io/seaport/tree/cookbook/docs/cookbook) (it definetely should be accepted and included in the project), I understand that Opensea strategy is to store the signed orders in their back end, and then they build the front end for an NFT using all these orders, signed by the offerers and ready to be fullfilled.

I'm interested in understanding the on-chain approach. What I understood so far is that we have to call the validate() function in Seaport smart contract in order to validate an order. But I can't find a way to retrieve these orders from the smart contract, neither from blockchain events, to build a front end that shows them to the fullfillers.

Do we need to store the orders off-chain anyway in this second use-case? So the flow would be the same as in the off-chain approach, but with an extra contract call from the offerer?

Thanks!

**Comment by neptuneeight** [comment]
Hi Narkuss, I've been using the validate function as well. it works great for cheaper chains since the incremental gas fee of the validation function call is immaterial. 

I agree with you, however, there is no way (as far as I am aware) to retrieve the validated orders from the chain directly, so not much of an advantage (again, as far as I am aware) over signatures stored off-chain.

what I have done is validated and then stored the order in a database, as you mentioned and then serve it up based on connected account.

There might be a better way to do this, but for now it is working ok.

**Comment by aegas-io** [comment]
Hi there,

When the order is validated on-chain, there's event `OrderValidated` that gets emitted in the `validate()` transaction. It doesn't contain the order parameters and offerer's signature in it, though the `validate()` call transaction data does. And these parameters are sufficient to fulfill the order for the fulfiller.

Theoretically, you could observe `OrderValidated` events, check out the transaction data by hash of transaction where the event occurred, and use it for fulfillment. 

Validate Example: https://goerli.etherscan.io/tx/0x444214e6baf4cc6ec3e087bdcaf7ad4a37f348a2ca0aeb9dedd2a336b1f3615c

Fulfill Example: https://goerli.etherscan.io/tx/0xa02ac253e5f4afdec3b89f3af9150f908a2404ee76d6300d5948ba3bab14714c

**Comment by neptuneeight** [comment]
agree that you can get the transaction data from the orderhash. I tried this first, but you do have to call each transaction from the blockchain each time and resolve the order status, so it is a bit cumbersome once there is multiple orders involved. what I found worked was to store the order data along with the orderhash (since I have to store this anyways) and then pull the entire order from a database, which is much more efficient.

after implementation I agree that there is no real advantage of the validate function over a signature, since you have to store both anyways. In my case, I am operating on polygon, so the incremental cost of the upfront validation is negligable (a couple of cents), so this approach was fine and I can market the product as all 'on-chain' - i'm not sure that helps, but it sounds cool lol

**Comment by narkuss** [comment]
Absolutely, it is much more efficient to store the order off-chain, the computation cost of retrieving the order parameters from the orderHash is too high. The zone approach would have the same problem, map events to transactions and then filter the data for the relevant contract, but having the advantage of being fully on-chain.

I think that for the web3 world, it is a good practice to try and make products all on-chain. And I'd bet that most of the products that anounce them as fully on-chain, are more off-chain than your approach.

Thanks!
