### ISSUE TITLE
gas free listing broken backward compatibility

### ISSUE THREAD

**Issue by syffs** [ProjectOpenSea/seaport#627]
Following seaport, I understand that `ProxyRegistry` and `proxies` are not used anymore. Hence this broke gas free listing for all the contracts that included pre-approval through `ProxyRegistry`.

You cannot claim to be improving gas with seaport if you're breaking gas free listing for all contracts that used to support it.
To be backward compatible, proxy registry should be updated to return `0x1E0049783F008A0085193E00003D00cd54003c71` as `proxies` for everyone. 

Also, [this](https://github.com/ProjectOpenSea/opensea-creatures/blob/master/contracts/ERC721Tradable.sol) should be updated.

**Comment by okyanu** [comment]
is there any seaport compatibility for existing contract includes ProxyRegistry function, existing contract listing problem about You must approve assets #for trading before creating an order 

I think you are right and opensea must support ProxyRegistry old contract 

I have a lot of trouble about existing contracts because of ProxyRegistry and I think many developer as well
